### ISSUE TITLE
Properties for your dataloader in this repository?

### ISSUE THREAD

**Issue by v-wewei** [erikwijmans/etw_pytorch_utils#5]
hi, erikwijmans
would you like to give an introduction about your dataloader ?  Is there any difference between the pytorch default dataloader?
also i am curious about the bn momentum and bn decay , since pytorch do not share bn decay default ?
 thanks very much !

**Comment by erikwijmans** [comment]
The primary difference is that the workers persist through epochs -- in the standard pytorch data loader, the workers a reset every epoch.  For certain datasets, this can have a pretty noticeable performance boost.

The momentum decay is something that was used in PointNet++ so I added it here for that.
